### ISSUE TITLE
FATAL ERROR: Upgrade failed

### ISSUE THREAD

**Issue by teunis90** [gplessis/dotdeb-mysql#12]
Today I installed Debian Wheezy as a clean install and added the dotdeb repository after, created a snapshot and tried to install mysql5.6 with Ansible.

After the installation I got an error message in my syslog:
Oct  8 15:01:26 prod5 mysqld: 2014-10-08 15:01:26 3574 [ERROR] Native table 'performance_schema'.'table_io_waits_summary_by_index_usage' has the wrong structure

This could be fixed by entering: "mysql_upgrade", but this should happen in the install script or init script. I found out that my init script does try to update but fail somehow. 

Oct  8 15:07:57 prod5 /etc/mysql/debian-start[5564]: Looking for 'mysql' as: /usr/bin/mysql
Oct  8 15:07:57 prod5 /etc/mysql/debian-start[5564]: Looking for 'mysqlcheck' as: /usr/bin/mysqlcheck
Oct  8 15:07:57 prod5 /etc/mysql/debian-start[5564]: FATAL ERROR: Upgrade failed
Oct  8 15:07:57 prod5 /etc/mysql/debian-start[5579]: Checking for insecure root accounts.
Oct  8 15:07:57 prod5 /etc/mysql/debian-start[5584]: Triggering myisam-recover for all MyISAM tables

Any clue if this is an general error or does this happen because I installed it via Ansible?

**Comment by gothick** [comment]
If it's any help to anyone in the future, I found that this error was because I had the wrong password for the debian-sys-maint user specified in /etc/mysql/debian.cnf, having restored all my databases from another server.
