### ISSUE TITLE
Update to 5.6.22?

### ISSUE THREAD

**Issue by tschundeee** [gplessis/dotdeb-mysql#13]
Current official release is 5.6.22 => dotdeb is 5.6.21

Changelog:
http://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-22.html

**Comment by gplessis** [comment]
Working on it

**Comment by mpingu** [comment]
Hello is there a Status on 5.6.22 ?

**Comment by gplessis** [comment]
I need some more free time to test it and release it, sorry for the delay.

**Comment by gplessis** [comment]
47ee9813dd3e40fde2282474b75087a800c2af3d includes MySQL 5.6.23. Packages are coming soon.
