### ISSUE TITLE
Install / upgrade fails with version 5.6.23-1~dotdeb.2_all

### ISSUE THREAD

**Issue by cm-rudolph** [gplessis/dotdeb-mysql#14]
Today's release fails to install on a fresh debian wheezy with following message:

    mkdir: cannot create directory `': No such file or directory
    dpkg: error processing mysql-server-5.6 (--configure):
     subprocess installed post-installation script returned error exit status 1

Upgrading a 5.6.23-1~dotdeb.1_all fails, too and leads to an unusable mysql server.

**Comment by cm-rudolph** [comment]
Complete log of upgrade is

    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages will be upgraded:
      libmysqlclient-dev libmysqlclient18 mysql-client-5.6 mysql-client-core-5.6 mysql-common mysql-common-5.6 mysql-server mysql-server-5.6 mysql-server-core-5.6
    9 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 47.0 MB of archives.
    After this operation, 0 B of additional disk space will be used.
    Do you want to continue [Y/n]?
    Get:1 http://packages.dotdeb.org/ wheezy/all libmysqlclient-dev amd64 5.6.23-1~dotdeb.2 [1,588 kB]
    Get:2 http://packages.dotdeb.org/ wheezy/all mysql-common all 5.6.23-1~dotdeb.2 [74.2 kB]
    Get:3 http://packages.dotdeb.org/ wheezy/all libmysqlclient18 amd64 5.6.23-1~dotdeb.2 [1,122 kB]
    Get:4 http://packages.dotdeb.org/ wheezy/all mysql-client-core-5.6 amd64 5.6.23-1~dotdeb.2 [6,708 kB]
    Get:5 http://packages.dotdeb.org/ wheezy/all mysql-client-5.6 amd64 5.6.23-1~dotdeb.2 [15.7 MB]
    Get:6 http://packages.dotdeb.org/ wheezy/all mysql-server-5.6 amd64 5.6.23-1~dotdeb.2 [14.5 MB]
    Get:7 http://packages.dotdeb.org/ wheezy/all mysql-server-core-5.6 amd64 5.6.23-1~dotdeb.2 [7,237 kB]
    Get:8 http://packages.dotdeb.org/ wheezy/all mysql-common-5.6 all 5.6.23-1~dotdeb.2 [72.5 kB]
    Get:9 http://packages.dotdeb.org/ wheezy/all mysql-server all 5.6.23-1~dotdeb.2 [72.1 kB]
    Fetched 47.0 MB in 4s (11.4 MB/s)
    Reading changelogs... Done
    Preconfiguring packages ...
    (Reading database ... 45909 files and directories currently installed.)
    Preparing to replace libmysqlclient-dev 5.6.23-1~dotdeb.1 (using .../libmysqlclient-dev_5.6.23-1~dotdeb.2_amd64.deb) ...
    Unpacking replacement libmysqlclient-dev ...
    Preparing to replace mysql-common 5.6.23-1~dotdeb.1 (using .../mysql-common_5.6.23-1~dotdeb.2_all.deb) ...
    Unpacking replacement mysql-common ...
    Preparing to replace libmysqlclient18:amd64 5.6.23-1~dotdeb.1 (using .../libmysqlclient18_5.6.23-1~dotdeb.2_amd64.deb) ...
    Unpacking replacement libmysqlclient18:amd64 ...
    Preparing to replace mysql-client-core-5.6 5.6.23-1~dotdeb.1 (using .../mysql-client-core-5.6_5.6.23-1~dotdeb.2_amd64.deb) ...
    Unpacking replacement mysql-client-core-5.6 ...
    Preparing to replace mysql-client-5.6 5.6.23-1~dotdeb.1 (using .../mysql-client-5.6_5.6.23-1~dotdeb.2_amd64.deb) ...
    Unpacking replacement mysql-client-5.6 ...
    Processing triggers for man-db ...
    Setting up mysql-common (5.6.23-1~dotdeb.2) ...
    (Reading database ... 45909 files and directories currently installed.)
    Preparing to replace mysql-server-5.6 5.6.23-1~dotdeb.1 (using .../mysql-server-5.6_5.6.23-1~dotdeb.2_amd64.deb) ...
    [ ok ] Stopping MySQL database server: mysqld.
    [ ok ] Stopping MySQL database server: mysqld.
    Unpacking replacement mysql-server-5.6 ...
    Preparing to replace mysql-server-core-5.6 5.6.23-1~dotdeb.1 (using .../mysql-server-core-5.6_5.6.23-1~dotdeb.2_amd64.deb) ...
    Unpacking replacement mysql-server-core-5.6 ...
    Preparing to replace mysql-common-5.6 5.6.23-1~dotdeb.1 (using .../mysql-common-5.6_5.6.23-1~dotdeb.2_all.deb) ...
    Unpacking replacement mysql-common-5.6 ...
    Preparing to replace mysql-server 5.6.23-1~dotdeb.1 (using .../mysql-server_5.6.23-1~dotdeb.2_all.deb) ...
    Unpacking replacement mysql-server ...
    Processing triggers for man-db ...
    Setting up libmysqlclient18:amd64 (5.6.23-1~dotdeb.2) ...
    Setting up libmysqlclient-dev (5.6.23-1~dotdeb.2) ...
    Setting up mysql-client-core-5.6 (5.6.23-1~dotdeb.2) ...
    Setting up mysql-client-5.6 (5.6.23-1~dotdeb.2) ...
    Setting up mysql-server-core-5.6 (5.6.23-1~dotdeb.2) ...
    Setting up mysql-server-5.6 (5.6.23-1~dotdeb.2) ...
    [ ok ] Stopping MySQL database server: mysqld.
    mkdir: cannot create directory `': No such file or directory
    dpkg: error processing mysql-server-5.6 (--configure):
     subprocess installed post-installation script returned error exit status 1
    Setting up mysql-common-5.6 (5.6.23-1~dotdeb.2) ...
    dpkg: dependency problems prevent configuration of mysql-server:
     mysql-server depends on mysql-server-5.6; however:
      Package mysql-server-5.6 is not configured yet.

    dpkg: error processing mysql-server (--configure):
     dependency problems - leaving unconfigured
    Errors were encountered while processing:
     mysql-server-5.6
     mysql-server
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by cm-rudolph** [comment]
`/usr/sbin/mysqld --verbose --help 2>/dev/null | awk '/^datadir\s/ { print $2 }'` returns an empty result. Removing the `\s` leads to the desired string (per default `/var/lib/mysql`).

**Comment by olessavluk** [comment]
I also have the same issue on debian 7.6

**Comment by cm-rudolph** [comment]
My quick and dirty workaround (just to get my mysql server running again) was to edit `/var/lib/dpkg/info/mysql-server-5.6.postinst` after the upgrade failed and to remove the `\s` from the line posted above. After removal I re-executed `apt-get upgrade` again.

**Comment by gplessis** [comment]
This should be fixed with the latest update, please confirm https://github.com/gplessis/dotdeb-mysql/commit/3f3f17cecf95d006554a8fc5aabc5609dd61ac24

**Comment by olessavluk** [comment]
reinstalled, no errors thrown
thank you!

**Comment by cm-rudolph** [comment]
Works here, too. Thanks.
