### ISSUE TITLE
mysql 5.6 for jessie

### ISSUE THREAD

**Issue by blindpet** [gplessis/dotdeb-mysql#16]
Will you be making a package for jessie? I can see it is available for wheezy through dotdeb.

**Comment by gplessis** [comment]
Sorry, but I won't provide MySQL 5.6 for Jessie. Why not switch to MariaDB?

**Comment by blindpet** [comment]
There are compatibility issues with plugins on Wordpress if I use backups running one version compared to another.

May I ask why you provided mysql 5.6 for wheezy?

Will you provide mariadb 10 for wheezy then?

Basically I'm trying to set up a test environment to migrate to php7, mariadb/mysql on wheezy to jessie. For obvious reasons versions should match to avoid any random issues.
