### ISSUE TITLE
MySQL 5.6.3x updates

### ISSUE THREAD

**Issue by Galixte** [gplessis/dotdeb-mysql#19]
Salut @gplessis,

as-tu planifié une mise à jour pour Wheezy de MySQL concernant les versions 5.6.3x publiées (http://dev.mysql.com/doc/relnotes/mysql/5.6/en/) ?

Encore merci pour ton travail.

Cordialement, Raphaël.

---------------------

Hi @gplessis,

do you have planed to update Wheezy to 5.6.3x versions of MySQL (http://dev.mysql.com/doc/relnotes/mysql/5.6/en/).

Thanks for your support !

Best regards, Raphaël.

**Comment by Galixte** [comment]
Thanks !

**Comment by Galixte** [comment]
Hi,

thanks for update to 5.6.33 ! I think it was very necessary : http://www.nextinpact.com/news/101344-mysql-chercheur-devoile-deux-failles-0-day-critiques.htm Maybe the next month too ;)

**Comment by Galixte** [comment]
Thanks for update !

**Comment by Galixte** [comment]
Hi @gplessis,

could you provide the 5.6.35 release, please ?

Regards !

**Comment by gplessis** [comment]
5.6.35 is now available

**Comment by Galixte** [comment]
Thanks !

**Comment by Galixte** [comment]
Hi @gplessis,

could you provide the 5.6.36 release, please ?

Regards !

**Comment by Galixte** [comment]
Hi @gplessis,

could you provide the 5.6.36 release, please ?

Regards !

**Comment by gplessis** [comment]
MySQL 5.6.36 for Wheezy is currently being uploaded to the main repo. Sorry for the delay.

**Comment by Galixte** [comment]
Aucun problème, merci 👍

**Comment by Galixte** [comment]
Hi @gplessis,

could you provide the 5.6.37 release, please ?

Regards !

**Comment by gplessis** [comment]
Packages of MySQL 5.6.37 are currently being uploaded.

(You should consider upgrading your boxes to Jessie or Stretch before Wheezy's EOL)

**Comment by Galixte** [comment]
Thanks! My migration to Stretch is planed for this winter.

**Comment by Galixte** [comment]
Hi @gplessis,

could you provide the 5.6.39 release: https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-39.html, please ?

Regards !

**Comment by Galixte** [comment]
Thanks!
