### ISSUE TITLE
mysql 5.6 for jessie?

### ISSUE THREAD

**Issue by f31n** [gplessis/dotdeb-mysql#20]
hi when is mysql 5.6 planned for jessie?
Any ideas?

regards

**Comment by gplessis** [comment]
I'm sorry, but I won't provide MySQL 5.6 for Jessie. Maybe you could migrate to mariadb-server, it's seamless.

**Comment by klemmster** [comment]
Could you please update the "https://www.dotdeb.org/about/" section then?
It claims to support "MySQL 5.6" 
and Jessie;
